import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Tạo tài khoản",
  description: "Generated by tuan anh",
};

export default function RegisterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
