import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Tài khoản",
  description: "Generated by tuan anh",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
