import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "/node_modules/primeflex/primeflex.css";
import type { Metadata } from "next";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { ScrollTop } from "primereact/scrolltop";
import "./globals.css";

export const metadata: Metadata = {
  title: "Áo Polo Nam Cao Cấp - Áo Thun Nam Cao Cấp Meriman",
  description: "Generated by tuan anh",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Header />
        <div> {children}</div>
        <Footer />
        <ScrollTop
          threshold={100}
          className="w-3rem h-3rem bg-primary"
          icon="pi pi-arrow-up text-base"
        />
      </body>
    </html>
  );
}
