import type { Metadata } from "next";
import Link from "next/link";
import { Image } from "primereact/image";
import logo from "./images/logo.webp";
export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by tuan anh",
};

export default function RegisterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="grid flex my-0">
      <div className="col-3 ">
        <div className="bg-[#000000] mt-3 ">
          <div className="mb-1 text-[#000000]">none</div>
          <div className="flex justify-center">
            <Image src={logo.src} alt="logo" />
          </div>
          <ul className="text-[#fff] text-[16px] font-[600] mt-2">
            <li className="py-4 flex  hover:bg-[#ccc] hover:text-[#000]">
              <Link href={"/admin"}>
                <i className="pi pi-user mr-2 ml-3"></i>Quản lý khách hàng
              </Link>
            </li>
            <li className="py-4 flex  hover:bg-[#ccc] hover:text-[#000]">
              <Link href={"/admin/categories"}>
                <i className="pi pi-list mr-2 ml-3"></i>Quản lý loại sản phẩm
              </Link>
            </li>
            <li className="py-4 flex hover:bg-[#ccc] hover:text-[#000]">
              <Link href={"/admin/products"}>
                <i className="pi pi-stop mr-2 ml-3"></i>Quản lý sản phẩm
              </Link>
            </li>
            <li className="py-4 flex  hover:bg-[#ccc] hover:text-[#000]">
              <Link href={"/admin/images-product"}>
                <i className="pi pi-images ml-3 mr-2"></i>Quản lý hình ảnh sản
                phẩm
              </Link>
            </li>
          </ul>
        </div>
      </div>
      <div className="col-9">
        <div className="mt-3 h-full">{children}</div>
      </div>
    </div>
  );
}
