import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Thông tin sản phẩm",
  description: "Generated by tuan anh",
};

export default function HeThongLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
